object Version {
    const val kotlin = "1.3.72"
    const val gradlePlugin = "4.0.0-beta04"
    const val appcompat = "1.1.0"
    const val androidxCoreKtx = "1.3.0-rc01"
    const val material = "1.2.0-alpha06"
    const val room = "2.2.5"
    const val coroutines = "1.3.6"
    const val testRunner = "1.1.1"
    const val espressoCore = "3.1.1"
    const val jUnit = "1.1.0"
    const val robolectric = "4.1"
    const val truth = "1.0.1"
    const val fragment = "1.3.0-alpha04"
    const val lifecycle = "2.3.0-alpha02"
    const val lifecycleArch = "2.1.0"
    const val navigation = "2.3.0-alpha06"
    const val koin = "2.1.5"
}